# Generated by Django 4.2.3 on 2025-09-27 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='documentscan',
            name='rawData',
            field=models.TextField(blank=True, null=True),
        ),
    ]
