# Generated by Django 4.2.3 on 2025-09-27 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_documentscan_rawdata'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='documentscan',
            name='status',
        ),
        migrations.AddField(
            model_name='documentscan',
            name='changeLevel',
            field=models.CharField(choices=[('No Change', 'No Change'), ('Low', 'Low'), ('Major', 'Major'), ('Critical', 'Critical')], default='No Change', max_length=50),
        ),
        migrations.AddField(
            model_name='documentscan',
            name='changeSummary',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='documentscan',
            name='currentSummary',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='documentscan',
            name='changes',
            field=models.BooleanField(default=False),
        ),
    ]
