# Generated by Django 4.2.3 on 2025-09-27 22:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_remove_documentscan_status_documentscan_changelevel_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='status',
            field=models.CharField(default='Healthy', max_length=50),
        ),
    ]
