# Generated by Django 4.2.3 on 2025-09-27 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_document_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='category',
            field=models.CharField(default='General', max_length=100, null=True),
        ),
    ]
