# Generated by Django 4.2.3 on 2025-09-28 00:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_document_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='documentscan',
            name='additions',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='documentscan',
            name='deletions',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='documentscan',
            name='modifications',
            field=models.TextField(blank=True, null=True),
        ),
    ]
